#! /bin/sh


# Put some of this in ~/.xinitrc is the settings are WM/DE agnostic?

# wal -Rn?  // xrdb
# greenclip
dunst &
# libinput-gestures
sxhkd &
polybar example &
picom &
mpd &
xwallpaper --stretch $(cat ~/.cache/wal/wal) &
# blueman-applet &

xsetroot -cursor_name left_ptr
unclutter &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Chromium desktop='^2' // focus-on //floating
bspc rule -a mpv state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a Kupfer.py focus=on

pc config bottom_padding          0
bspc config auto_cancel             true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config auto_alternate          true

trap 'jobs -p | xargs kill' EXIT # TODO: What the hell is that?

# https://github.com/desyncr/bspwmrc/blob/master/init
# https://github.com/janpansa/bspwm/blob/master/bspwmrc
# https://github.com/odsod/bspwmrc
# https://github.com/altrgeek/bspwm-polybar/blob/master/.config/bspwm/bspwmrc
# https://github.com/keystroke3/dotfiles/blob/master/bspwm/autostart.sh
# https://github.com/keystroke3/dotfiles/blob/master/bspwm/bspwmrc
# https://github.com/styamsingh/dotfiles/blob/master/bspwm/bspwmrc
# https://github.com/lll2yu/dotfiles-naavi/blob/master/.config/bspwm/bspwmrc
# https://github.com/morpheusthewhite/dotfiles/blob/master/.config/bspwm/bspwmrc
# https://github.com/morpheusthewhite/dotfiles/blob/master/.config/bspwm/bspwm.conf
# https://github.com/yousufinternet/config-files/blob/master/.config/bspwm/bspwmrc
# https://github.com/connor-brooks/dotfiles/blob/master/bspwmrc
# https://github.com/null4bl3/dotfiles/tree/master/bspwm
# https://github.com/onosendi/dotfiles/tree/master/.config/bspwm
# https://github.com/Andrflor/arch-setup/blob/master/config/home/.config/bspwm/bspwmrc
